# Lab 1: Tensor Manipulation

imports

In [4]:
import numpy as np
import torch


ModuleNotFoundError: No module named 'torch'

1D Array with NumPy

In [3]:

t = np.array([0., 1., 2., 3., 4., 5., 6.])
print(t)


[0. 1. 2. 3. 4. 5. 6.]


In [5]:
print('Rank  of t: ', t.ndim)
print('Shape of t: ', t.shape)

Rank  of t:  1
Shape of t:  (7,)


In [6]:
print('t[0] t[1] t[-1] = ', t[0], t[1], t[-1]) # Element
print('t[2:5] t[4:-1]  = ', t[2:5], t[4:-1])   # Slicing
print('t[:2] t[3:]     = ', t[:2], t[3:])      # Slicing

t[0] t[1] t[-1] =  0.0 1.0 6.0
t[2:5] t[4:-1]  =  [2. 3. 4.] [4. 5.]
t[:2] t[3:]     =  [0. 1.] [3. 4. 5. 6.]


2D Array with NumPy

In [7]:
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
print(t)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [8]:
print('Rank  of t: ', t.ndim)
print('Shape of t: ', t.shape)

Rank  of t:  2
Shape of t:  (4, 3)


PyTorch is like NumPy (but better)

1D Array with PyTorch

In [9]:
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print(t)

NameError: name 'torch' is not defined

In [10]:
print(t.dim())  # rank
print(t.shape)  # shape
print(t.size()) # shape
print(t[0], t[1], t[-1])  # Element
print(t[2:5], t[4:-1])    # Slicing
print(t[:2], t[3:])       # Slicing

AttributeError: 'numpy.ndarray' object has no attribute 'dim'

2D Array with PyTorch

In [11]:
t = torch.FloatTensor([[1., 2., 3.],
                       [4., 5., 6.],
                       [7., 8., 9.],
                       [10., 11., 12.]
                      ])
print(t)

NameError: name 'torch' is not defined

In [12]:
print(t.dim())  # rank
print(t.size()) # shape
print(t[:, 1])
print(t[:, 1].size())
print(t[:, :-1])

AttributeError: 'numpy.ndarray' object has no attribute 'dim'

Shape, Rank, Axis

In [13]:
t = torch.FloatTensor([[[[1, 2, 3, 4],
                         [5, 6, 7, 8],
                         [9, 10, 11, 12]],
                       [[13, 14, 15, 16],
                        [17, 18, 19, 20],
                        [21, 22, 23, 24]]
                       ]])

NameError: name 'torch' is not defined

In [14]:
print(t.dim())  # rank  = 4
print(t.size()) # shape = (1, 2, 3, 4)

AttributeError: 'numpy.ndarray' object has no attribute 'dim'

Frequently Used Operations in PyTorch

Mul vs. Matmul

In [15]:
print()
print('-------------')
print('Mul vs Matmul')
print('-------------')
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print(m1.matmul(m2)) # 2 x 1

m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print(m1 * m2) # 2 x 2
print(m1.mul(m2))


-------------
Mul vs Matmul
-------------


NameError: name 'torch' is not defined

Broadcasting


In [16]:
# Same shape
m1 = torch.FloatTensor([[3, 3]])
m2 = torch.FloatTensor([[2, 2]])
print(m1 + m2)

NameError: name 'torch' is not defined

In [18]:
# Vector + scalar
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([3]) # 3 -> [[3, 3]]
print(m1 + m2)

NameError: name 'torch' is not defined

In [17]:
# 2 x 1 Vector + 1 x 2 Vector
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([[3], [4]])
print(m1 + m2)

NameError: name 'torch' is not defined

Mean

In [19]:
t = torch.FloatTensor([1, 2])
print(t.mean())

NameError: name 'torch' is not defined

In [20]:
# Can't use mean() on integers
t = torch.LongTensor([1, 2])
try:
    print(t.mean())
except Exception as exc:
    print(exc)

NameError: name 'torch' is not defined

In [21]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

NameError: name 'torch' is not defined

In [22]:
print(t.mean())
print(t.mean(dim=0))
print(t.mean(dim=1))
print(t.mean(dim=-1))

6.5


TypeError: _mean() got an unexpected keyword argument 'dim'

Sum

In [23]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

NameError: name 'torch' is not defined

In [24]:
print(t.sum())
print(t.sum(dim=0))
print(t.sum(dim=1))
print(t.sum(dim=-1))

78.0


TypeError: _sum() got an unexpected keyword argument 'dim'

Max and Argmax

In [25]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

NameError: name 'torch' is not defined

In [26]:
print(t.max()) # Returns one value: max

12.0


In [27]:
print(t.max(dim=0)) # Returns two values: max and argmax
print('Max: ', t.max(dim=0)[0])
print('Argmax: ', t.max(dim=0)[1])

TypeError: _amax() got an unexpected keyword argument 'dim'

In [28]:
print(t.max(dim=1))
print(t.max(dim=-1))

TypeError: _amax() got an unexpected keyword argument 'dim'

View

In [29]:
t = np.array([[[0, 1, 2],
               [3, 4, 5]],

              [[6, 7, 8],
               [9, 10, 11]]])
ft = torch.FloatTensor(t)
print(ft.shape)

NameError: name 'torch' is not defined

In [30]:
print(ft.view([-1, 3]))
print(ft.view([-1, 3]).shape)

NameError: name 'ft' is not defined

In [31]:
print(ft.view([-1, 1, 3]))
print(ft.view([-1, 1, 3]).shape)

NameError: name 'ft' is not defined

Squeeze

In [32]:
ft = torch.FloatTensor([[0], [1], [2]])
print(ft)
print(ft.shape)

NameError: name 'torch' is not defined

In [33]:
print(ft.squeeze())
print(ft.squeeze().shape)

NameError: name 'ft' is not defined

In [34]:
ft = torch.Tensor([0, 1, 2])
print(ft.shape)

NameError: name 'torch' is not defined

In [35]:
print(ft.unsqueeze(0))
print(ft.unsqueeze(0).shape)

NameError: name 'ft' is not defined

In [36]:
print(ft.view(1, -1))
print(ft.view(1, -1).shape)

NameError: name 'ft' is not defined

In [37]:
print(ft.unsqueeze(1))
print(ft.unsqueeze(1).shape)

NameError: name 'ft' is not defined

In [38]:
print(ft.unsqueeze(-1))
print(ft.unsqueeze(-1).shape)

NameError: name 'ft' is not defined

Scatter (for one-hot encoding)

In [39]:
lt = torch.LongTensor([[0], [1], [2], [0]])
print(lt)

NameError: name 'torch' is not defined

In [40]:
one_hot = torch.zeros(4, 3) # batch_size = 4, classes = 3
one_hot.scatter_(1, lt, 1)
print(one_hot)

NameError: name 'torch' is not defined

Casting

In [41]:
lt = torch.LongTensor([1, 2, 3, 4])
print(lt)

NameError: name 'torch' is not defined

In [42]:
print(lt.float())

NameError: name 'lt' is not defined

In [43]:
bt = torch.ByteTensor([True, False, False, True])
print(bt)

NameError: name 'torch' is not defined

In [44]:
print(bt.long())
print(bt.float())

NameError: name 'bt' is not defined

Concatenation

In [45]:
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])

NameError: name 'torch' is not defined

In [46]:
print(torch.cat([x, y], dim=0))
print(torch.cat([x, y], dim=1))

NameError: name 'torch' is not defined

Stacking

In [47]:
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])

NameError: name 'torch' is not defined

In [48]:
print(torch.stack([x, y, z]))
print(torch.stack([x, y, z], dim=1))

NameError: name 'torch' is not defined

In [49]:
print(torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim=0))

NameError: name 'torch' is not defined

Ones and Zeros Like

In [50]:
x = torch.FloatTensor([[0, 1, 2], [2, 1, 0]])
print(x)

NameError: name 'torch' is not defined

In [51]:
print(torch.ones_like(x))
print(torch.zeros_like(x))

NameError: name 'torch' is not defined

In-place Operation

In [52]:
x = torch.FloatTensor([[1, 2], [3, 4]])

NameError: name 'torch' is not defined

In [53]:
print(x.mul(2.))
print(x)
print(x.mul_(2.))
print(x)

NameError: name 'x' is not defined

Miscellaneous

Zip

In [54]:
for x, y in zip([1, 2, 3], [4, 5, 6]):
    print(x, y)

1 4
2 5
3 6


In [55]:
for x, y, z in zip([1, 2, 3], [4, 5, 6], [7, 8, 9]):
    print(x, y, z)

1 4 7
2 5 8
3 6 9
